### PR TITLE
Share session options among all the sessions created by one context

### LINKED ISSUE #74: Fail early when creating the context if the OpenVINO EP is not supported

### PR DESCRIPTION
**Pull request by mingmingtasd**
fix #74 

The session options are created when creating context, and are shared among all the sessions created by this context.

PTAL, thanks!

### CODE REVIEW

**Comment by mingmingtasd** [comment]
> Please rebase your code since PR #173 landed, thanks!

Thanks, done.

File: services/webnn/ort/context_impl_ort.h [hunk 1]
```diff
@@ -49,6 +70,10 @@ class ContextImplOrt final : public WebNNContextImpl {
 
   ScopedOrtEnvPtr env_;
 
+  // The session options are shared among all the sessions created by this
+  // context.
+  scoped_refptr<SessionOptions> session_options_;
```
[the remark this answers is not in the document]
Comment (mingmingtasd) [reply services/webnn/ort/context_impl_ort.h:75]: In previous code, we need create session options when calling `Build()` each time for each graph, I just think the session options is same under one context, and it can load the ov dlls during `CreateContext()` stage to reduce the overhead if `Build()`.

File: services/webnn/webnn_context_provider_impl.cc [hunk 2]
```diff
@@ -141,6 +144,150 @@ bool ShouldCreateDmlContext(const mojom::CreateContextOptions& options) {
...
+constexpr char kOVPrecision[] = "precision";
+constexpr char kOVCacheDir[] = "cache_dir";
+// Values:
+constexpr char kOVDeviceType[] = "device_type";
+constexpr char kOVDeviceGPU[] = "GPU";
+constexpr char kOVDeviceCPU[] = "CPU";
+constexpr char kOVDeviceNPU[] = "NPU";
+
+base::expected<ort::ScopedOrtSessionOptions, mojom::ErrorPtr>
+CreateSessionOptions(const mojom::CreateContextOptions::Device device_type) {
```
Comment (huningxin) [inline services/webnn/webnn_context_provider_impl.cc:167]: I'd recommend to have this method as a static method of `SessionOptions`. And move it's implementation to services/webnn/ort/context_impl_ort.cc. WDYT?

Comment (mingmingtasd) [reply services/webnn/webnn_context_provider_impl.cc]: Good idea! Done and rebase. PTAL again, thanks!
