### PR TITLE
Fix the slice op issue when using ORT DML EP

### LINKED ISSUE #212: Slice op execution fails on ORT DML EP
One of the `Slice` op in [stable diffusion model](https://webai.sh.intel.com:8080/demos/stable-diffusion-1.5/) fails to execute when using ORT DML EP:

Image

ORT DML EP will [validate the arguments of `Slice` op](https://github.com/microsoft/onnxruntime/blob/67216c89965731898a252b23cbcc681a0465c540/onnxruntime/core/providers/dml/OperatorAuthorHelper/OperatorHelper.cpp#L1044) but the SD model's `Slice` op inputs don't meet these requirements.

Image

To reproduce:

```
chrome.exe --enable-logging --v=2 --no-sandbox --enable-features=WebNNOrt,WebNNOrtDml --use-redist-ort "https://webai.sh.intel.com:8080/demos/stable-diffusion-1.5/"
```

### PR DESCRIPTION
**Pull request by miaobin**
Fix #212 
@huningxin PTAL, thanks!

### CODE REVIEW

File: services/webnn/ort/graph_builder_ort.cc [hunk 1]
```diff
@@ -3069,10 +3069,15 @@ GraphBuilderOrt::AddSliceOperation(const mojom::Slice& slice) {
     steps[i] = base::checked_cast<int64_t>(slice.ranges[i].stride);
   }
 
-  // Axes is an optional input, if not provided, it is an empty string and will
-  // be treated as [0, 1, …, len(starts) - 1]:
-  // https://onnx.ai/onnx/operators/onnx__Slice.html#inputs
-  const std::string axes = "";
+  // Explicitly provide axes to meet the requirements of different EPs.
+  base::FixedArray<int64_t> axes_sizes(slice.ranges.size());
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc:3073]: `axes_sizes` sounds a bit confusing, how about `axes_values`?

File: services/webnn/ort/graph_builder_ort.cc [hunk 2]
```diff
@@ -3069,10 +3069,15 @@ GraphBuilderOrt::AddSliceOperation(const mojom::Slice& slice) {
...
+  for (size_t i = 0; i < slice.ranges.size(); i++) {
+    axes_sizes[i] = base::checked_cast<int64_t>(i);
+  }
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc:3076]: How about using `std::iota(axes_values.begin(), axes_values.end(), 0)` rather than a loop?

**Review by huningxin — APPROVED** [review]
LGTM!

File: services/webnn/ort/graph_builder_ort.cc (hunk 1 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.
