### PR TITLE
Clamp the indices for GatherND

### LINKED ISSUE #141: [GatherND] Clamp the indices to prevent out-of-bound reading
If the index is out-of-bound, both OV CPU and GPU EP will throw runtime error: promise_test: Unhandled rejection with value: object "InvalidStateError: Failed to execute 'readTensor' on 'MLContext': Tensor has been destroyed or context is lost."

Error log
> [23740:13264:0218/125723.200:FATAL:graph_impl_ort.cc(121)] : NOTREACHED hit. [WebNN] Ort Status: Non-zero status code returned while running GatherND node. Name:'_0' Status Message: invalid index found, index = 20
 base::debug::CollectStackTrace [0x00007FFB4BFDA055+21]
 base::debug::StackTrace::StackTrace [0x00007FFB4BFEB2FC+236]
 logging::LogMessage::Flush [0x00007FFB4C08F542+210]
 logging::LogMessage::~LogMessage [0x00007FFB4C08F409+25]
 logging::NotReachedNoreturnError::NotReachedNoreturnError [0x00007FFB4C0AF3EE+1518]
 logging::CheckNoreturnError::~CheckNoreturnError [0x00007FFB4C0AEC5B+11]
 webnn::ort::GraphImplOrt::ComputeResources::OrtRunSync [0x00007FFB54145986+2198]
 base::internal::Invoker<base::internal::FunctorTraits<void (__cdecl webnn::ort::GraphImplOrt::ComputeResources::*&& __ptr64)(std::__Cr::vector<std::__Cr::pair<std::__Cr::basic_string<char,std::__Cr::char_traits<char>,std::__Cr::allocator<char> >,OrtValue  [0x00007FFB54145A07+119]
 base::OnceCallback<void __cdecl(void)>::Run [0x00007FFB4472CF3D+141]
 base::internal::PostTaskAndReplyRelay::RunTaskAndPostReply [0x00007FFB4C00D9B7+103]
 base::internal::Invoker<base::internal::FunctorTraits<void (__cdecl*&& __ptr64)(base::internal::PostTaskAndReplyRelay),base::internal::PostTaskAndReplyRelay && __ptr64>,base::internal::BindState<0,1,0,void (__cdecl*)(base::internal::PostTaskAndReplyRelay) [0x00007FFB4C00DB46+54]
 base::OnceCallback<void __cdecl(void)>::Run [0x00007FFB4472CF3D+141]
 base::TaskAnnotator::RunTaskImpl [0x00007FFB4C0237A4+340]
 base::internal::TaskTracker::RunSkipOnShutdown [0x00007FFB501D2C78+200]
 base::internal::TaskTracker::RunTask [0x00007FFB501D2057+1159]
 base::internal::TaskTracker::RunAndPopNextTask [0x00007FFB501D1844+772]
 base::internal::WorkerThread::RunWorker [0x00007FFB52965281+1073]
 base::internal::WorkerThread::RunPooledWorker [0x00007FFB52964CD8+24]
 base::PlatformThreadBase::GetCurrentThreadPriorityForTest [0x00007FFB4BFB5634+660]
 BaseThreadInitThunk [0x00007FFC13D7259D+29]
 RtlUserThreadStart [0x00007FFC15A2AF38+40]

### PR DESCRIPTION
**Pull request by shiyi9801**
Fix #141

### CODE REVIEW

**Comment by shiyi9801** [comment]
GatherND WPTs on OV EP previously all fall back to CPU EP, with this patch, only one case (gatherND float32 4D input and 1D uint32 indices) falls back. And the test result for different EPs:
On CPU EP, all tests can run pass.
On OV CPU, the test results are expected  (only negative indices get wrong results).
On OV GPU, the out-of-bound test cases can run pass, but some tests unexpectedly throw runtime error during readTensor:
> [15544:11424:0321/144304.544:FATAL:graph_impl_ort.cc(122)] : NOTREACHED hit. [WebNN] Ort Status: Non-zero status code returned while running OpenVINO-EP-subgraph_2 node. Name:'OpenVINOExecutionProvider_OpenVINO-EP-subgraph_2_0' Status Message: D:\onnxruntime\onnxruntime\core\providers\openvino\ov_interface.cc:249 void __cdecl onnxruntime::openvino_ep::OVInferRequest::WaitRequest(void) [OpenVINO-EP]  Wait Model Failed: Exception from src\inference\src\cpp\infer_request.cpp:245:
Check 'ov::shape_size(port.get_shape()) == ov::shape_size(mem_shape)' failed at src\plugins\intel_gpu\src\plugin\sync_infer_request.cpp:420:
[GPU] Unexpected elements count for output tensor

**Comment by shiyi9801** [comment]
About the performance, I tested two models (MoveNet-singlepose-lightning and MoveNet-singlepose-thunder) that have some GatherND ops, and I didn't observe obvious performance regression from this patch.

File: services/webnn/ort/graph_builder_ort.cc [hunk 1]
```diff
@@ -594,6 +594,35 @@ GraphBuilderOrt::ClampIndices(std::string_view indices,
...
+GraphBuilderOrt::Clamp(std::string_view input,
+                       base::span<const uint32_t> shape,
+                       base::span<const DataType> min_value,
+                       base::span<const DataType> max_value) {
+  ASSIGN_OR_RETURN(std::string min,
+                   CreateInitializer<DataType>(shape, min_value));
+  ASSIGN_OR_RETURN(std::string max,
+                   CreateInitializer<DataType>(shape, max_value));
+
+  // max(input_value, min_value)
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc:609]: Nit:
```suggestion
  // max_output = max(input_value, min_value)
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 2]
```diff
@@ -594,6 +594,35 @@ GraphBuilderOrt::ClampIndices(std::string_view indices,
...
+  const std::string max_node = GenerateNextOperationName("inserted_max");
+  const std::string max_output = GenerateNextOperandName();
+  std::array<const char*, 2> max_inputs = {input.data(), min.c_str()};
+  std::array<const char*, 1> max_outputs = {max_output.c_str()};
+  model_editor_.AddNode(kOpTypeMax, max_node, max_inputs, max_outputs);
+
+  // min(input_value, max_value)
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc:616]: Nit:
```suggestion
  // min_output = min(max_output, max_value)
```

**Review by huningxin — APPROVED** [review]
LGTM with a nit

File: services/webnn/ort/graph_builder_ort.cc (hunk 1 above)
Comment (shiyi9801) [reply services/webnn/ort/graph_builder_ort.cc]: Done!

**Review by huningxin — APPROVED** [review]
