### PR TITLE
fix crash issue for L2Poo2d

### LINKED ISSUE #96: [WPT][L2Poo2d] All l2poo2d tests will crash
image

### PR DESCRIPTION
**Pull request by mingmingtasd**
Fix #96 

PTAL, thanks!

### CODE REVIEW

File: services/webnn/ort/graph_builder_ort.cc [hunk 1]
```diff
@@ -1249,8 +1249,9 @@ void GraphBuilderOrt::AddPool2dOperation(const mojom::Pool2d& pool2d) {
     }
     case mojom::Pool2d::Kind::kL2Pool2d: {
       op_type = kOpTypeLpPool2d;
-      attributes.push_back(model_builder_.CreateAttribute(
-          /*name=*/"p", static_cast<int64_t>(2)));
+      attr_p =
```
Comment (shiyi9801) [inline services/webnn/ort/graph_builder_ort.cc:1252]: `attributes.push_back(model_builder_.CreateAttribute(
          /*name=*/"p", static_cast<int64_t>(2)).Release());` ?

**Comment by mingmingtasd** [comment]
Addressed comments, PTAL again, thanks!

**Review by shiyi9801 — APPROVED** [review]
👍

**Review by huningxin — COMMENTED** [review]
👍 , thanks for the fixing!
