### PR TITLE
Handle bool output is used by both bool input and uint8 input

### LINKED ISSUE #217: Safety Checker build failed after eliminate redundant cast ops
Image

If an ONNX operator with a bool output is followed by more than two paths that need bool and uint8 as input respectively, an error will be reported.

### PR DESCRIPTION
**Pull request by miaobin**
Fix #217 
If a bool output operand is used as bool input and not used as uint8 input at the same time, it can skip inserting cast operator to/from uint8.

This is not the optimal solution (for example the original WebNN model):
```
    Less
    /   \
Where   Add   
```
Current optimized ONNX model:
```
Less
  | 
Cast ---
  |     |
Cast    |
  |     |
Where  Add   
```
Desired optimized ONNX model:
```
 Less
  |  \
  |   Cast 
  |     |
Where  Add   
```

If we want to optimize to the desired model, we need to check nodes before adding each node that support uint8 as input.  Such detailed  processing may cause maintenance challenges, especially when adding new operators. WDYT? @huningxin

### CODE REVIEW

**Comment by miaobin** [comment]
cc @mingmingtasd

File: services/webnn/ort/graph_builder_ort.cc [hunk 1]
```diff
@@ -505,13 +506,161 @@ void GraphBuilderOrt::FindBoolOperands() {
...
 
-  // Find all operands that can skip cast operators. If an operand is a bool
-  // output and also used as bool input, it can skip inserting cast operator
-  // to/from uint8.
+  // Find all operands that can skip cast operators. If a bool output operand is
+  // used as bool input and not used as uint8 input at the same time, it can
+  // skip inserting cast operator to/from uint8.
   for (auto id : bool_output_operands) {
-    if (bool_input_operands.count(id)) {
+    if (bool_input_operands.count(id) && !uint8_input_operands.count(id)) {
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Could we keep the previous `bool_operands_` and add `uint8_input_operands_`?

When adding a node that has bool output, such as `lesser`, if its output is used by a node that requires a uint8 input (in `uint8_input_operands`), such as `add`, appending a `cast`.

When adding a node that has bool input, such as 'where', if its input is an bool operand (e.g. in `bool_operands_`), use it directly without prepending a `cast`.

Would it lead us to the desired solution?
```
Less
  |  \
  |   Cast 
  |     |
Where  Add  
```

Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Thanks for your suggestion from another perspective, which led us to the desired solution!
Now we introduced `bool_to_uint8_operands_` set to store operands that should be inserted cast operators from bool to uint8 data type. And introduced `bool_to_uint8_operands_` map to map operand and bool operand. Please take another look, thanks a lot!

File: services/webnn/ort/graph_builder_ort.cc [hunk 2]
```diff
@@ -505,15 +506,169 @@ void GraphBuilderOrt::FindBoolOperands() {
       default:
         break;
     }
+
+    // Find all operands that can used as uint8 input.
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]:
```suggestion
    // Find all operands that are used as uint8 input.
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 3]
```diff
@@ -505,15 +506,169 @@ void GraphBuilderOrt::FindBoolOperands() {
...
+    switch (operation->which()) {
+      case mojom::Operation::Tag::kArgMinMax: {
+        const auto& arg_min_max = *operation->get_arg_min_max();
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc:513]: Should we check whether the input is uint8?

File: services/webnn/ort/graph_builder_ort.cc [hunk 4]
```diff
@@ -505,15 +506,169 @@ void GraphBuilderOrt::FindBoolOperands() {
...
+        uint8_input_operands.insert(gather_elements.input_operand_id);
+        break;
+      }
+      case mojom::Operation::Tag::kGatherNd: {
+        const auto& gather_nd = *operation->get_gather_nd();
+        uint8_input_operands.insert(gather_nd.input_operand_id);
+        break;
+      }
+      case mojom::Operation::Tag::kPad: {
+        // https://github.com/shiyi9801/chromium/issues/85
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Expand this comment into a TODO:
```suggestion
        // TODO(https://github.com/shiyi9801/chromium/issues/85): handle uint8 input once pad supports uint8 input.
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 5]
```diff
@@ -505,15 +506,169 @@ void GraphBuilderOrt::FindBoolOperands() {
...
+        uint8_input_operands.insert(where.true_value_operand_id);
+        uint8_input_operands.insert(where.false_value_operand_id);
+        break;
+      }
+      default:
+        break;
+    }
+  }
+
+  // The output operands can also be viewed as the uint8 input operands.
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]:
```suggestion
  // The graph output operands can also be viewed as the uint8 input operands.
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 6]
```diff
@@ -505,15 +506,169 @@ void GraphBuilderOrt::FindBoolOperands() {
...
+  for (const auto& output_operand_id : graph_info_->output_operands) {
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc:658]: Again, should we check whether the graph output is uint8?

File: services/webnn/ort/graph_builder_ort.cc [hunk 7]
```diff
@@ -505,15 +506,169 @@ void GraphBuilderOrt::FindBoolOperands() {
...
+    uint8_input_operands.insert(output_operand_id);
   }
 
-  // Find all operands that can skip cast operators. If an operand is a bool
-  // output and also used as bool input, it can skip inserting cast operator
-  // to/from uint8.
   for (auto id : bool_output_operands) {
+    // Find all operands that can skip cast operators. If an operand is a bool
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]:
```suggestion
    // Find all operands that may skip cast operators. If an operand is a bool
```

File: services/webnn/ort/graph_builder_ort.h [hunk 8]
```diff
@@ -340,6 +340,12 @@ class GraphBuilderOrt {
   // operators to/from uint8 data type.
   std::unordered_set<uint64_t> bool_operands_;
 
+  // Operands that should be inserted cast operators from bool to uint8.
+  std::unordered_set<uint64_t> bool_to_uint8_operands_;
+
+  // Operands that mapped to bool operands after inserting the cast operators.
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.h]:
```suggestion
  // Map the uint8 operands back to bool operands after inserting the cast operators.
```

File: services/webnn/ort/graph_builder_ort.h [hunk 9]
```diff
@@ -340,6 +340,12 @@ class GraphBuilderOrt {
...
+  std::unordered_map<std::string, std::string> operand_to_bool_operand_;
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.h]:
```suggestion
  std::unordered_map<std::string, std::string> uint8_to_bool_operands_map_;
```

File: services/webnn/ort/graph_builder_ort.h [hunk 10]
```diff
@@ -340,6 +340,12 @@ class GraphBuilderOrt {
   // operators to/from uint8 data type.
   std::unordered_set<uint64_t> bool_operands_;
 
+  // Operands that should be inserted cast operators from bool to uint8.
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.h]:
```suggestion
  // Bool operands that should casted to uint8.
```

File: services/webnn/ort/graph_builder_ort.h [hunk 11]
```diff
@@ -340,6 +340,12 @@ class GraphBuilderOrt {
...
+  std::unordered_set<uint64_t> bool_to_uint8_operands_;
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.h]:
```suggestion
  std::unordered_set<uint64_t> bool_operands_to_be_casted_to_uint8_;
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 12]
```diff
@@ -945,9 +1100,19 @@ void GraphBuilderOrt::AddElementWiseLogicalOperation(
       if (!bool_operands_.count(element_wise_binary->lhs_operand_id)) {
         lhs = PrependCast(lhs, ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL);
       }
+      // If the current operand is inserted a cast, find the bool operand
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]:
```suggestion
      // If the current operand is casted from bool, find and use the bool operand
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 13]
```diff
@@ -945,9 +1100,19 @@ void GraphBuilderOrt::AddElementWiseLogicalOperation(
...
+      // through the original operand.
+      if (bool_to_uint8_operands_.count(element_wise_binary->lhs_operand_id)) {
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Make it else, because bool_operands_ should have this input operand for this case:
```suggestion
      else if (bool_to_uint8_operands_.count(element_wise_binary->lhs_operand_id)) {
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 14]
```diff
@@ -945,9 +1100,19 @@ void GraphBuilderOrt::AddElementWiseLogicalOperation(
...
+        lhs = operand_to_bool_operand_[lhs];
+      }
       if (!bool_operands_.count(element_wise_binary->rhs_operand_id)) {
         rhs = PrependCast(rhs, ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL);
       }
+      // If the current operand is inserted a cast, find the bool operand
+      // through the original operand.
+      if (bool_to_uint8_operands_.count(element_wise_binary->rhs_operand_id)) {
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Same here

File: services/webnn/ort/graph_builder_ort.cc [hunk 15]
```diff
@@ -959,30 +1124,40 @@ void GraphBuilderOrt::AddElementWiseLogicalOperation(
...
-            mojom::ElementWiseUnary::Kind::kLogicalNot &&
-        !bool_operands_.count(element_wise_unary->input_operand_id)) {
-      lhs = PrependCast(lhs, ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL);
+        mojom::ElementWiseUnary::Kind::kLogicalNot) {
+      if (!bool_operands_.count(element_wise_unary->input_operand_id)) {
+        lhs = PrependCast(lhs, ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL);
+      }
+      // If the current operand is inserted a cast, find the bool operand
+      // through the original operand.
+      if (bool_to_uint8_operands_.count(element_wise_unary->input_operand_id)) {
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Same, else if

File: services/webnn/ort/graph_builder_ort.cc [hunk 16]
```diff
@@ -3197,7 +3375,11 @@ void GraphBuilderOrt::AddWhereOperation(const mojom::Where& where) {
   if (!bool_operands_.count(where.condition_operand_id)) {
     condition = PrependCast(condition, ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL);
   }
-
+  // If the current operand is inserted a cast, find the bool operand through
+  // the original operand.
+  if (bool_to_uint8_operands_.count(where.condition_operand_id)) {
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Same, use else if

File: third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js [hunk 17]
```diff
@@ -128,6 +128,105 @@ const optimizedgraphTests = [
       }
     }
   },
+  {
+    'name': 'Lesser + Where & output: [Less] -> Bool -> [Where] & [Less] -> [Cast] -> uint8(output)',
```
Comment (huningxin) [inline third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js]: Keep the name simple, add a comment that illustrating the topology
```suggestion
    'name': 'Lesser output is consumed by Where and used as graph output',
```

File: third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js [hunk 18]
```diff
@@ -128,6 +128,105 @@ const optimizedgraphTests = [
...
+        },
+        'whereOutput': {
+          'data': [1.1],
+          'descriptor': {shape: [1], dataType: 'float32'}
+        }
+      }
+    }
+  },
+  {
+    'name': 'Lesser + Where & Add: [Less] -> Bool -> [Where] & [Less] -> Bool -> [Cast] -> uint8 -> [Add]',
```
Comment (huningxin) [inline third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js]: Do the same here
```suggestion
    'name': 'Lesser output is consumed by Where and Add',
```

File: services/webnn/ort/graph_builder_ort.cc (hunk 2 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Changed to "Find all operands that may be used as uint8 input." Will perform set intersection between these and all the operands that are bool output latter.

File: services/webnn/ort/graph_builder_ort.cc (hunk 3 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc:513]: The current model has been verified, so the bool output operands found above must be followed by the nodes that require uint8 input. When we perform set intersection between `bool_output_operands` and `may_uint8_input_operands`. We can get the uint8 input operands that need insert cast operators (from bool to uint8).

File: services/webnn/ort/graph_builder_ort.cc (hunk 4 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 5 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 6 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc:658]: As explained above.

File: services/webnn/ort/graph_builder_ort.cc (hunk 7 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 12 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 13 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 14 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 15 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 16 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.h (hunk 11 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.h]: Done.

File: services/webnn/ort/graph_builder_ort.h (hunk 8 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.h]: Done.

File: services/webnn/ort/graph_builder_ort.h (hunk 9 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.h]: Done.

File: third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js (hunk 17 above)
Comment (miaobin) [reply third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js]: Done.

File: third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js (hunk 18 above)
Comment (miaobin) [reply third_party/blink/web_tests/external/wpt/webnn/conformance_tests/optimize_graph.https.any.js]: Done.

**Review by miaobin — COMMENTED** [review]
Update the code to improve variable names and comments. Please take another look, thanks a lot!

File: services/webnn/ort/graph_builder_ort.cc [hunk 19]
```diff
@@ -449,8 +449,9 @@ GraphBuilderOrt::CreateScalarInitializer(const DataType& value) {
 void GraphBuilderOrt::FindBoolOperands() {
   std::unordered_set<uint64_t> bool_output_operands;
   std::unordered_set<uint64_t> bool_input_operands;
+  std::unordered_set<uint64_t> may_uint8_input_operands;
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Nit: maybe
```suggestion
  std::unordered_set<uint64_t> maybe_uint8_input_operands;
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 20]
```diff
@@ -959,30 +1127,40 @@ void GraphBuilderOrt::AddElementWiseLogicalOperation(
...
-  } else {
+  if (bool_operands_to_be_casted_to_uint8_.count(output_operand_id)) {
     const std::string bool_output = GenerateNextOperandName();
     std::array<const char*, 1> bool_outputs = {bool_output.c_str()};
     model_editor_.AddNode(op_type, node, inputs, bool_outputs);
     ONNXTensorElementDataType output_type =
         OperandTypeToONNXTensorElementDataType(
             GetOperand(output_operand_id).descriptor.data_type());
     AppendCast(bool_output, output, output_type);
+    // Store the mapping between the original operand and the bool operand after
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]:
```suggestion
    // Store the mapping between the casted operand and the original bool operand after
```

File: services/webnn/ort/graph_builder_ort.cc [hunk 21]
```diff
@@ -1019,6 +1194,12 @@ void GraphBuilderOrt::AddElementWiseLogicalNotEqualOperation(
...
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.cc]: Same here

File: services/webnn/ort/graph_builder_ort.h [hunk 22]
```diff
@@ -340,6 +340,13 @@ class GraphBuilderOrt {
   // operators to/from uint8 data type.
   std::unordered_set<uint64_t> bool_operands_;
 
+  // Bool operands that should casted to uint8.
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.h]:
```suggestion
  // Bool operands that should be casted to uint8.
```

File: services/webnn/ort/graph_builder_ort.h [hunk 23]
```diff
@@ -340,6 +340,13 @@ class GraphBuilderOrt {
...
+  std::unordered_set<uint64_t> bool_operands_to_be_casted_to_uint8_;
+
+  // Map the uint8 operands back to bool operands after inserting the cast
```
Comment (huningxin) [inline services/webnn/ort/graph_builder_ort.h]:
```suggestion
  // Map the uint8 operands back to the bool operands after inserting the cast
```

**Review by huningxin — APPROVED** [review]
LGTM with nits

File: services/webnn/ort/graph_builder_ort.cc (hunk 19 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 20 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.cc (hunk 21 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.cc]: Done.

File: services/webnn/ort/graph_builder_ort.h (hunk 22 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.h]: Done.

File: services/webnn/ort/graph_builder_ort.h (hunk 23 above)
Comment (miaobin) [reply services/webnn/ort/graph_builder_ort.h]: Done.

**Review by miaobin — COMMENTED** [review]
@huningxin  Thanks for your detailed review and feedback! PTAL, thanks!

**Review by huningxin — APPROVED** [review]
LGTM
